FROM docker.io/library/python:slim

WORKDIR /app
COPY ./pyproject.toml pyproject.toml

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y netcat \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --ansi

EXPOSE 5000/tcp

CMD python manage.py runserver 0.0.0.0:5000