# Generated by Django 3.2.4 on 2021-07-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=30, unique=True, verbose_name='Descrição')),
                ('code', models.PositiveSmallIntegerField(null=True, verbose_name='Código')),
                ('nature', models.CharField(choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1, verbose_name='Natureza')),
                ('signal', models.CharField(max_length=1, verbose_name='Sinal')),
            ],
            options={
                'ordering': ['id', 'created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data da Compra')),
                ('hour', models.TimeField(verbose_name='Hora da Compra')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Compra')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('customer_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customercard')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transactiontype')),
            ],
            options={
                'unique_together': {('date', 'hour', 'value', 'type', 'customer', 'customer_card')},
            },
        ),
    ]
